import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "@tanstack/react-start/config";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
	tsr: {
		appDirectory: "src",
		routeTreeFileHeader: [
			"/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */",
		],
		quoteStyle: "double",
	},
	server: {
		preset: "bun",
		esbuild: {
			options: {
				target: "esnext",
			},
		},
	},
	vite: {
		plugins: [
			tailwindcss(),
			tsConfigPaths({
				projects: ["./tsconfig.json"],
			}),
		],
	},
});
