/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AppAccountImport } from "./routes/_app/account";
import { Route as AppPostPostIdImport } from "./routes/_app/post.$postId";
import { Route as AppRouteImport } from "./routes/_app/route";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
	id: "/_app",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const AppAccountRoute = AppAccountImport.update({
	id: "/account",
	path: "/account",
	getParentRoute: () => AppRouteRoute,
} as any);

const AppPostPostIdRoute = AppPostPostIdImport.update({
	id: "/post/$postId",
	path: "/post/$postId",
	getParentRoute: () => AppRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/_app": {
			id: "/_app";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AppRouteImport;
			parentRoute: typeof rootRoute;
		};
		"/_app/account": {
			id: "/_app/account";
			path: "/account";
			fullPath: "/account";
			preLoaderRoute: typeof AppAccountImport;
			parentRoute: typeof AppRouteImport;
		};
		"/_app/post/$postId": {
			id: "/_app/post/$postId";
			path: "/post/$postId";
			fullPath: "/post/$postId";
			preLoaderRoute: typeof AppPostPostIdImport;
			parentRoute: typeof AppRouteImport;
		};
	}
}

// Create and export the route tree

interface AppRouteRouteChildren {
	AppAccountRoute: typeof AppAccountRoute;
	AppPostPostIdRoute: typeof AppPostPostIdRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
	AppAccountRoute: AppAccountRoute,
	AppPostPostIdRoute: AppPostPostIdRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
	AppRouteRouteChildren,
);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"": typeof AppRouteRouteWithChildren;
	"/account": typeof AppAccountRoute;
	"/post/$postId": typeof AppPostPostIdRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"": typeof AppRouteRouteWithChildren;
	"/account": typeof AppAccountRoute;
	"/post/$postId": typeof AppPostPostIdRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/_app": typeof AppRouteRouteWithChildren;
	"/_app/account": typeof AppAccountRoute;
	"/_app/post/$postId": typeof AppPostPostIdRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "" | "/account" | "/post/$postId";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "" | "/account" | "/post/$postId";
	id: "__root__" | "/" | "/_app" | "/_app/account" | "/_app/post/$postId";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	AppRouteRoute: typeof AppRouteRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AppRouteRoute: AppRouteRouteWithChildren,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/account",
        "/_app/post/$postId"
      ]
    },
    "/_app/account": {
      "filePath": "_app/account.tsx",
      "parent": "/_app"
    },
    "/_app/post/$postId": {
      "filePath": "_app/post.$postId.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
